name: PlanIt
description: Plan it and Organize.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity:
  cupertino_icons:
  email_validator:
  firebase_auth:
  firebase_core:
  flutter_local_notifications: ^3.0.2
  flutter_native_timezone: ^1.0.4
  flutter_svg:
  fluttertoast:
  get:
  get_it:
  http: ^0.12.2
  intl:
  material_design_icons_flutter:
  path_provider:
  provider:
  rxdart: ^0.25.0
  shared_preferences:
  sprintf: ^5.0.0
  sqflite: ^1.3.2+1
  sqflite_migration_service: ^1.0.4
  table_calendar:
  timezone: ^0.5.9
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icons/squircle_planit.png"
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/sql/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
