name: plan_it
description: Plan it and Organize.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity:
  cupertino_icons:
  email_validator:
  firebase_auth:
  firebase_core:
  flutter_local_notifications: ^4.0.0
  flutter_native_timezone: ^1.0.4
  flutter_svg: ^0.19.3
  fluttertoast:
  get:
  get_it:
  http: ^0.12.2
  intl:
  material_design_icons_flutter:
  path_provider:
  provider:
  rxdart: ^0.25.0
  shared_preferences:
  sprintf: ^5.0.0
  sqflite: ^1.3.2+1
  sqflite_migration_service: ^1.0.4
  table_calendar:
  timezone: ^0.6.1
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/sql/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
