name: PlanIt
description: Plan it and Organize.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg:
  intl:
  get:
  table_calendar:
  cupertino_icons:
  fluttertoast:
  provider:
  email_validator:
  get_it:
  path_provider:
  url_launcher:
  material_design_icons_flutter:
  connectivity:
  firebase_auth:
  shared_preferences:
  firebase_core:
  sqflite: ^1.3.2+1
  sqflite_migration_service: ^1.0.4
  rxdart: ^0.25.0
  flutter_local_notifications: ^3.0.2
  http: ^0.12.2
  timezone: ^0.5.9
  flutter_native_timezone: ^1.0.4

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/sql/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
